// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesRepository.Data;

#nullable disable

namespace SalesRepository.Migrations
{
    [DbContext(typeof(SalesDBContext))]
    [Migration("20251108083548_SuppliersGrid2")]
    partial class SuppliersGrid2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SalesModel.Models.TblBranch", b =>
                {
                    b.Property<int>("Branch_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Branch_ID"));

                    b.Property<DateTime?>("Branch_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Branch_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Branch_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Branch_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Branch_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Branch_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Branch_ID");

                    b.ToTable("TblBranch");
                });

            modelBuilder.Entity("SalesModel.Models.TblCustomer", b =>
                {
                    b.Property<int>("Customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customer_ID"));

                    b.Property<DateTime?>("Customer_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Customer_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Customer_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customer_ID");

                    b.ToTable("TblCustomer");
                });

            modelBuilder.Entity("SalesModel.Models.TblDailyMovement", b =>
                {
                    b.Property<int>("DailyMovement_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyMovement_ID"));

                    b.Property<DateTime?>("DailyMovement_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DailyMovement_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DailyMovement_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DailyMovement_UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DailyMovement_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DailyMovement_ID");

                    b.ToTable("TblDailyMovements");
                });

            modelBuilder.Entity("SalesModel.Models.TblDailyMovementDetails", b =>
                {
                    b.Property<int>("DailyMovementDetails_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyMovementDetails_ID"));

                    b.Property<DateTime?>("DailyMovementDetails_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DailyMovementDetails_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyMovementDetails_MovementID")
                        .HasColumnType("int");

                    b.Property<string>("DailyMovementDetails_Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DailyMovementDetails_PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DailyMovementDetails_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DailyMovementDetails_ProductID")
                        .HasColumnType("int");

                    b.Property<int>("DailyMovementDetails_Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyMovementDetails_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DailyMovementDetails_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DailyMovementDetails_ID");

                    b.HasIndex("DailyMovementDetails_MovementID");

                    b.HasIndex("DailyMovementDetails_ProductID");

                    b.ToTable("TblDailyMovementDetails");
                });

            modelBuilder.Entity("SalesModel.Models.TblDailyMovementExpenses", b =>
                {
                    b.Property<int>("DailyMovementExpense_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyMovementExpense_ID"));

                    b.Property<decimal>("DailyMovementExpense_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DailyMovementExpense_CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DailyMovementExpense_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DailyMovementExpense_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyMovementExpense_MovementID")
                        .HasColumnType("int");

                    b.Property<string>("DailyMovementExpense_Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyMovementExpense_Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyMovementExpense_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DailyMovementExpense_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DailyMovementExpense_ID");

                    b.HasIndex("DailyMovementExpense_CategoryID");

                    b.HasIndex("DailyMovementExpense_MovementID");

                    b.ToTable("TblDailyMovementExpenses");
                });

            modelBuilder.Entity("SalesModel.Models.TblDailyMovementSuppliers", b =>
                {
                    b.Property<int>("DailyMovementSupplier_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyMovementSupplier_ID"));

                    b.Property<decimal>("DailyMovementSupplier_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DailyMovementSupplier_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DailyMovementSupplier_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyMovementSupplier_MovementID")
                        .HasColumnType("int");

                    b.Property<string>("DailyMovementSupplier_Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyMovementSupplier_SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("DailyMovementSupplier_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DailyMovementSupplier_ID");

                    b.HasIndex("DailyMovementSupplier_MovementID");

                    b.HasIndex("DailyMovementSupplier_SupplierID");

                    b.ToTable("TblDailyMovementSuppliers");
                });

            modelBuilder.Entity("SalesModel.Models.TblExpense_Item", b =>
                {
                    b.Property<int>("ExpenseItem_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseItem_ID"));

                    b.Property<DateTime?>("ExpenseItem_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseItem_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpenseItem_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseItem_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpenseItem_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseItem_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseItem_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseItem_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseItem_ID");

                    b.ToTable("TblExpense_Item");
                });

            modelBuilder.Entity("SalesModel.Models.TblProduct", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_ID"));

                    b.Property<DateTime?>("Product_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Product_CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Product_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Product_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Product_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Product_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Product_ID");

                    b.HasIndex("Product_CategoryID");

                    b.ToTable("TblProduct");
                });

            modelBuilder.Entity("SalesModel.Models.TblProduct_Category", b =>
                {
                    b.Property<int>("ProductCategory_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategory_ID"));

                    b.Property<DateTime?>("ProductCategory_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCategory_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductCategory_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCategory_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductCategory_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCategory_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategory_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategory_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategory_ID");

                    b.ToTable("TblProduct_Category");
                });

            modelBuilder.Entity("SalesModel.Models.TblSupplier", b =>
                {
                    b.Property<int>("Supplier_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Supplier_ID"));

                    b.Property<DateTime?>("Supplier_AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Supplier_AddUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Supplier_DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Supplier_DeleteUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Supplier_EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Supplier_EditUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Visible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Supplier_ID");

                    b.ToTable("TblSupplier");
                });

            modelBuilder.Entity("SalesModel.Models.TblVat", b =>
                {
                    b.Property<int>("VatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VatID"));

                    b.Property<double>("VatPercent")
                        .HasColumnType("float");

                    b.Property<double>("VatValue")
                        .HasColumnType("float");

                    b.HasKey("VatID");

                    b.ToTable("TblVat");
                });

            modelBuilder.Entity("SalesModel.Models.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("SalesModel.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("Branch_ID")
                        .HasColumnType("int");

                    b.Property<int>("CashBalanceBank_ID")
                        .HasColumnType("int");

                    b.Property<int>("CashBalance_ID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Branch_ID");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SalesModel.Models.TblDailyMovementDetails", b =>
                {
                    b.HasOne("SalesModel.Models.TblDailyMovement", "DailyMovement")
                        .WithMany("DailyMovementDetails")
                        .HasForeignKey("DailyMovementDetails_MovementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesModel.Models.TblProduct", "Product")
                        .WithMany()
                        .HasForeignKey("DailyMovementDetails_ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMovement");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesModel.Models.TblDailyMovementExpenses", b =>
                {
                    b.HasOne("SalesModel.Models.TblExpense_Item", "ExpenseItem")
                        .WithMany()
                        .HasForeignKey("DailyMovementExpense_CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesModel.Models.TblDailyMovement", "DailyMovement")
                        .WithMany("DailyMovementExpenses")
                        .HasForeignKey("DailyMovementExpense_MovementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMovement");

                    b.Navigation("ExpenseItem");
                });

            modelBuilder.Entity("SalesModel.Models.TblDailyMovementSuppliers", b =>
                {
                    b.HasOne("SalesModel.Models.TblDailyMovement", "DailyMovement")
                        .WithMany()
                        .HasForeignKey("DailyMovementSupplier_MovementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesModel.Models.TblSupplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("DailyMovementSupplier_SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMovement");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SalesModel.Models.TblProduct", b =>
                {
                    b.HasOne("SalesModel.Models.TblProduct_Category", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("Product_CategoryID");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("SalesModel.Models.ApplicationUser", b =>
                {
                    b.HasOne("SalesModel.Models.TblBranch", "TblBranch")
                        .WithMany()
                        .HasForeignKey("Branch_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblBranch");
                });

            modelBuilder.Entity("SalesModel.Models.TblDailyMovement", b =>
                {
                    b.Navigation("DailyMovementDetails");

                    b.Navigation("DailyMovementExpenses");
                });
#pragma warning restore 612, 618
        }
    }
}
